# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: node builder

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-node@v4
      # with:
      #  node-version: 20.11.1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: env info
        run: ls & pwd
      - name: Get version
        id: get_version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: build
        run: pnpm build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Login to Aliyun Container Registry (ACR)
      #uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      #with:
      #login-server: registry.cn-shanghai.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
      #region-id: cn-shanghai # 务必正确填写镜像容器服务的登录地址
      #username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
      #password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hyfree/frontend:${{env.APP_VERSION}}
